language: go
go:
- 1.6.x
- 1.7.x
script: make test
notifications:
  slack:
    secure: myd3r2VxIFKob42CfdI73niCS9rvZcayP/FZQhF+yEsyFEAbayTDhAVNzAbick6BCmoG8cAGfHdk5QMpouLw2g6G7F4P6IrDbX3jDIPhX5B4DH6LaKJBu2yf3v5VVQT6J7yDlwditxsO333U/HrVZgeNLL5EBFQZSVSc1eU54JLvFXC4pScd3g3+qfdP5Us6rsKHrbqOyejstmrZo/lnnqg+PlTpajjv/hwcu26+Vqy8/HiMM48OtTaAKiatwiSN7cmnuAQg8/iLHrGmWMbKsahrkT6j8hlyBsGc2ILbCx7OrrtKoIWz/UX9WhECVE2/DJ2FAHiNw2skz/8xmZkRXWf0fs+VP9YLjhUBhhtt94PO5ckTdetWO3+lRjDn7snxQqJ9M0OowbHc8V2mo+oHiXgRf6Wu7iJegzw8C+UPFQIs4pkamCO33Pmi8WAx1449qZ4E2O4tAzfvXsjEApYGnSkEKU5NQI6m+iIRwt7szmva/sTa/h30EuzOhyejnvfBL+JhHMcyu2E7YpLHtbC8/Zc14/RgTuQxeqagvESsKcc4fDr0JmD+ZDYgddCL9+4SE6tvwF5ocqIWZe1EmgppSsgn7HxKImPwWufEOaVLDqE55Vk4NymyFZWHfC7E2lOyMgW6eTGmqlfcJcirYqpgY9OFo3YDhHt1aLE6jkuH+qI=
